- name: Configure Compute nodes
  hosts: compute
  roles:
    - repository-config


- name: Configure Controller nodes
  hosts: control 
  roles:
    - repository-config
    - setswap

- name: Configure deployment
  hosts: deployment
  roles:
    - repository-config
    - setswap
    - compute-cinder    
    - pre-deployment
    - deployment
